apiVersion: v1
kind: ServiceAccount
metadata:
  name: qwelli-sa
  namespace: qwelli
  annotations:
    # Workload identity annotation - replace with output from terraform
    azure.workload.identity/client-id: "${POD_IDENTITY_CLIENT_ID}"
  labels:
    azure.workload.identity/use: "true"
    app: qwelli
