syntax = "proto3";

package qwelli.v1;

option go_package = "github.com/karim-daw/qwelli/api/gen/go/qwelli/v1;v1;";

service SearchService {
    rpc Search(SearchRequest) returns (SearchResponse) {}
}

message SearchRequest {
    string query = 1;
    string folder_path = 2;
}

message SearchResponse {
    repeated string results = 1;
}

// generated command line commands
// protoc --go_out=. --go_opt=module=github.com/karim-daw/qwelli --go-grpc_out=. --go-grpc_opt=module=github.com/karim-daw/qwelli api/proto/search.proto